// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDWbu4UFLv2jOpIsdpixmJ8hL9bGcN3yB4',
//     appId: '1:762123751763:android:137b06ff4eafddff62d1a6',
//     messagingSenderId: '762123751763',
//     projectId: 'edoc-tabcom',
//     storageBucket: 'edoc-tabcom.appspot.com',
//   );

//   // static const FirebaseOptions ios = FirebaseOptions(
//   //   apiKey: 'AIzaSyD3Qnjr054Tqy0UfCWEB4vgLT3YWyd4nb4',
//   //   appId: '1:762123751763:ios:708da534101d450762d1a6',
//   //   messagingSenderId: '762123751763',
//   //   projectId: 'edoc-tabcom',
//   //   storageBucket: 'edoc-tabcom.appspot.com',
//   //   iosBundleId: 'mobifone.com.smartf',
//   // );
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD3Qnjr054Tqy0UfCWEB4vgLT3YWyd4nb4',
//     appId: '1:762123751763:ios:52b7500fd4f9900162d1a6',
//     messagingSenderId: '762123751763',
//     projectId: 'edoc-tabcom',
//     storageBucket: 'edoc-tabcom.appspot.com',
//     iosBundleId: 'vn.dft.smartf',
//   );
// }
